services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  api:
    environment:
      REDIS_URL: "redis://redis:6379"
    build:
      context: .
    command: api
    ports:
      - 8000:8000
    depends_on:
      - redis

  job:
    environment:
      REDIS_URL: "redis://redis:6379"
    build:
      context: .
    command: job
    depends_on:
      - redis
