[package]
name = "job"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.26.1"
serde_json = "1.0.122"
tungstenite = { version = "0.23.0", features = ["native-tls"] }
url = "2.5.2"

lib = { path = "../lib" }