[package]
name = "rest"
version = "0.0.1"
publish = false
edition = "2021"


[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.204"
serde_json = "1.0.122"

lib = { path = "../lib" }

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["deadpool_redis"]
